"use client";

import { useState, useEffect } from "react";
import { AdminHeader, AdminPrimaryGrid } from "@/components/admin";
import { Breadcrumb } from "@/components/layouts/Breadcrumb";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { PanelTablePagination } from "@/components/panel/PanelTablePagination";
import { PanelEmptyState } from "@/components/panel/PanelEmptyState";
import { Download, FileText } from "lucide-react";
import { getAdminReports, type AdminReportRow } from "@/services/apiAdmin";

const PAGE_SIZE = 10;

interface ReportRow {
  id: string;
  type: string;
  period: string;
  status: string;
  generatedBy: string;
  createdAt: string;
}

function mapApiToReportRow(r: AdminReportRow): ReportRow {
  const created = (r.created_at ?? "").slice(0, 19).replace("T", " ");
  return {
    id: r.id,
    type: "Skin report",
    period: (r.created_at ?? "").slice(0, 7),
    status: "Ready",
    generatedBy: (r.user_id ?? "").slice(0, 8) || "—",
    createdAt: created || "—",
  };
}

export default function AdminReportsPage() {
  const [page, setPage] = useState(1);
  const [typeFilter, setTypeFilter] = useState("all");
  const [reports, setReports] = useState<ReportRow[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getAdminReports()
      .then((data) => setReports(data.map(mapApiToReportRow)))
      .finally(() => setLoading(false));
  }, []);

  const filtered = typeFilter === "all" ? reports : reports.filter((r) => r.type === typeFilter);
  const paginated = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  return (
    <>
      <AdminHeader
        title="Reports"
        subtitle="Generated reports and exports."
        breadcrumb={<Breadcrumb />}
        actions={
          <Button size="sm">
            <Download className="h-4 w-4 mr-2" />
            Generate report
          </Button>
        }
      />

      <AdminPrimaryGrid>
        <Card className="border-border/60">
          <div className="p-4 border-b border-border/60">
            <Select value={typeFilter} onValueChange={setTypeFilter}>
              <SelectTrigger className="w-44">
                <SelectValue placeholder="Report type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All types</SelectItem>
                <SelectItem value="Skin report">Skin report</SelectItem>
              </SelectContent>
            </Select>
          </div>
          {loading ? (
            <div className="p-6 text-sm text-muted-foreground">Loading reports…</div>
          ) : filtered.length === 0 ? (
            <PanelEmptyState
              icon={<FileText className="h-12 w-12" />}
              title="No reports"
              description="Generated reports will appear here."
            />
          ) : (
          <>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>ID</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Period</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Generated by</TableHead>
                <TableHead>Created</TableHead>
                <TableHead className="w-24">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {paginated.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="text-muted-foreground font-mono text-xs">{r.id}</TableCell>
                  <TableCell className="font-medium">{r.type}</TableCell>
                  <TableCell className="text-muted-foreground">{r.period}</TableCell>
                  <TableCell className="text-muted-foreground">{r.status}</TableCell>
                  <TableCell className="text-muted-foreground">{r.generatedBy}</TableCell>
                  <TableCell className="text-muted-foreground">{r.createdAt}</TableCell>
                  <TableCell>
                    <Button variant="ghost" size="sm">
                      <Download className="h-4 w-4" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          <PanelTablePagination
            page={page}
            setPage={setPage}
            totalItems={filtered.length}
            pageSize={PAGE_SIZE}
          />
          </>
          )}
        </Card>
      </AdminPrimaryGrid>
    </>
  );
}
